name: build

on:
  release:
    types: [published]

jobs:
  build:
    name: build-and-release
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: build
        shell: pwsh
        run: Invoke-Expression "$(pwd)/win/build/ahk2exe.exe /in $(pwd)/win/main.ahk /out $(pwd)/Keyput-Methoard.exe /icon $(pwd)/win/build/icon.ico /base $(pwd)/win/build/autohotkey64.exe"

      - name: release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: Keyput-Methoard.exe
          token: ${{ secrets.GITHUB_TOKEN }}
